### ISSUE TITLE
Press release timezone issues

### ISSUE THREAD

**Issue by nickstenning** [okfn/foundation#105]
Something a little bit odd going on here with timezones. I would expect the admin interface to display times in my local timezone (which it appears to, setting the time correctly when I click "now") but it seems like the interpretation of the submitted time is UTC.

This might be the most sensible way of doing things (especially with people from all around the world trying to coordinate when releases are published) but it needs to be clearer in the admin interface what timezone I'm selecting in... and ideally clicking "now" would set the time to "now in UTC"...

*Copied from https://github.com/okfn/foundation/pull/103#issuecomment-36354172*

**Comment by morchickit** [comment]
WONTFIX. UTC is enough for now. :-)
