### ISSUE TITLE
Update Facebook and Twitter icons

### ISSUE THREAD

**Issue by nickstenning** [okfn/foundation#115]
... to reflect new designs from brand agency.
![social-sprite](https://f.cloud.github.com/assets/3602/2483995/942dcda0-b107-11e3-939b-9c55e825f0d0.png)

**Comment by morchickit** [comment]
@smth - your thoughts on the matter?

**Comment by smth** [comment]
This has been done https://github.com/okfn/foundation/commit/fa5358b1a3721303588c48d7e26b1f6e656d1d10
