### ISSUE TITLE
link style in header bars

### ISSUE THREAD

**Issue by nealbastek** [okfn/foundation#134]
It's currently set to the same green as the background color in the block so the links effectively disappear. 

Generally I've tried to avoid links in the blurb space copy, but it's the only space for free text on the network group nodes and I really need to have links there.

Example:
https://next.okfn.org/get-involved/global-network/argentina/

Can we update the style? If that's not possible let's talk about a workaround for the network group nodes.

**Comment by morchickit** [comment]
@smth can you have a look at this?
