### ISSUE TITLE
add g+ field to network group app

### ISSUE THREAD

**Issue by nealbastek** [okfn/foundation#136]
1. g+ 
2. wiki page link (e.g. http://wiki.okfn.org/Chapters/Brazil) {guessing there's probably a wiki icon in the kit somewhere, if you have a choice lean towards the one that most connotes 'community wiki'}

**Comment by nigelbabu** [comment]
Fixed in https://github.com/okfn/foundation/commit/e28499235d6d3402dc21ff6b7bf36781bf50d46e

**Comment by nigelbabu** [comment]
Bah, needs wiki link as well.

**Comment by nigelbabu** [comment]
Added wiki link in https://github.com/okfn/foundation/commit/237bf4a12b6e760281f5e5fb1c5ed7080d7fdf52
