### ISSUE TITLE
network map or directory

### ISSUE THREAD

**Issue by nealbastek** [okfn/foundation#139]
I didn't see a ticket for this, but it may be covered elsewhere. We need some formatting for the map and/or directory widget for the network groups on this page:

https://next.okfn.org/get-involved/global-network/

I am fine with the simplest of solutions that shows the breadth of the whole network (Ideally somewhere near the top of that page, 'above the fold')

Minimum requirements are a map with any reasonable highlighting technique to show we have a presence in a given country or a list of countries and flags . (Note: we only need to show the flag and the country name.)

It would be nice to have a section in the directory with header for 'Chapters' and a section with header for 'Local Groups', but we do not need to add those words to the item labels in the individual country directory i.e. not Spain Chapter, not China Local Group.

**Comment by pwalsh** [comment]
WONTFIX.
