### ISSUE TITLE
Content license: BY vs. BY-SA

### ISSUE THREAD

**Issue by tryggvib** [okfn/foundation#177]
Tore Hoel raised an issue on Twitter [about us using CC-BY-SA instead of CC-BY](https://twitter.com/tore/status/456002555454455808). This license was chosen in the end because we use images under CC-BY-SA which means that if we use it as part of our work, our work is then also CC-BY-SA.

But as Tore suggests we could also use CC-BY and [explain the exceptions](https://twitter.com/tore/status/456031557049147392).

Both of those work (although I personally like CC-BY-SA more, but the code is MIT which is more akin to CC-BY). We should pick one now as we haven't started putting any contributions on the page yet so we can still manage the re-licensing.

@LaurieJ, @nealbastek do you have any opinions?

**Comment by mlinksva** [comment]
I was recently [reminded](https://lists.okfn.org/pipermail/okfn-discuss/2015-April/thread.html#10888) of this when looking at okfn.org/ip-policy again. Also noted 'atribution' misspelling (missing a t). I'd submit a patch but searching this repository does not turn up that spelling, so the text must be in a database? In any case both the spelling on ip-policy and the incorrect license noted in the site footer ought be fixed.
