### ISSUE TITLE
"what is open?" links to /opendata but should go to a page for Open Definition, also reduce data-centricity

### ISSUE THREAD

**Issue by wolftune** [okfn/foundation#183]
This is just a piece of a site that looks to the world to be only about data. The phrase "what is open?" is also confusing to some.

What *is* open? (with italics) is superior. And the URL it should link to should be /open or /open-definition or /definition and it should be about open rather than data.

I suggest that since the site is already live, change the tagline to "Empowering people by freeing ideas" as a working non-data-centric tagline while discussions continue about finalizing all these things. To keep the "world" stuff below it, you could just add "We envision an Open world…"

**Comment by daonb** [comment]
Seems like it's fixed.

**Comment by morchickit** [comment]
FIXED
