### ISSUE TITLE
United Kingdom links

### ISSUE THREAD

**Issue by harry-wood** [okfn/foundation#198]
This URL https://okfn.org/network/united-kingdom/  goes to Open Knowledge Scotland, which is odd  (Also get to it via the "United Kingdom" link above that in the hierarchy)

**Comment by morchickit** [comment]
WONTFIX

**Comment by harry-wood** [comment]
any ...reason?

**Comment by morchickit** [comment]
Because:
1. We can give the Scotland flag to on the site (which is a different issue that we need to deal with).
2. Because we need to include more content about the English group. 
So closing this issue and will open two new ones later today.
