### ISSUE TITLE
United States links

### ISSUE THREAD

**Issue by RichardLitt** [okfn/foundation#206]
There are some dead links in the [US Page](https://okfn.org/network/united-states/). 

More importantly, is there any way for me to edit this myself? Why isn't this hosted on an open platform where I can PR changes like this?

**Comment by morchickit** [comment]
FIXED

**Comment by RichardLitt** [comment]
@morchickit Still curious about the questions I asked.

**Comment by morchickit** [comment]
You can't edit the page yourself, it has a Django CMS system. :-)

**Comment by RichardLitt** [comment]
Ok, thanks.
