### ISSUE TITLE
Attach new files 

### ISSUE THREAD

**Issue by lucychambers** [okfn/foundation#222]
On this page: https://okfn.org/training/

Please attach the following file in place of the existing course over each instance of "Course plan and course prerequisites. Contact us for details" as the overviews there are out of date: 

http://assets.okfn.org/Open-Data-Services.pdf

The same file should replace all three links for the one day course, data managers course and portal course. 

The using data overview should remain untouched.

**Comment by morchickit** [comment]
WONTFIX
