### ISSUE TITLE
events pages could be easier to navigate

### ISSUE THREAD

**Issue by LaurieJ** [okfn/foundation#225]
From https://okfn.org/get-involved/ -> "find an event near you" -> https://okfn.org/get-involved/events/ which has a nice listing of international events but nothing near me. This phrasing should link direct to : http://www.meetup.com/OpenKnowledgeFoundation/  (I think). 

Also it was hard to find the meetup list at all, i read the main body of https://okfn.org/get-involved/events/ and assumed there was no local events, but then i found a tiny link in the sidebar!  We should have the *same content* linked from the explanatory text on a page as in the sidebar, here.

**Comment by morchickit** [comment]
WONTFIX
