### ISSUE TITLE
Projects page not visible

### ISSUE THREAD

**Issue by rgrp** [okfn/foundation#234]
I raised this at go-live and it was also asked on list: https://lists.okfn.org/pipermail/okfn-discuss/2014-April/010267.html

I got sense at the time that we wanted to put it up but we were still tweaking project info for some projects ...

**Comment by morchickit** [comment]
Currently, there is not even one page that summaries all of our projects on the site. This page is not in any of the toolbars - https://okfn.org/projects/
@svanderwaal - what do you want to do with this page?

**Comment by pwalsh** [comment]
Mor, Neal, Nigel and I started looking at this already. Almost all the code is in place already. Pls leave this open.

**Comment by morchickit** [comment]
OK, after a call with Paul, closing this and opening a new one about the project page.
