### ISSUE TITLE
Broken link for OKF-meetup page

### ISSUE THREAD

**Issue by anderspeders** [okfn/foundation#237]
This page: https://okfn.org/get-involved/events/

links to this broken link: 
http://www.meetup.com/OpenKnowledgeFoundation/

**Comment by nealbastek** [comment]
just remove the link and any reference to it from the page, we are no longer using meetup. 

if anyone needs data from the old meetup group contact local@okfn.org

**Comment by nigelbabu** [comment]
The link is now deleted. Closing the issue.

**Comment by macoo222** [comment]
Ucelovo
