### ISSUE TITLE
Search button says "fl"

### ISSUE THREAD

**Issue by nigelbabu** [okfn/foundation#240]
Also, next to the search button is 'fl' instead of an arrow or something that clearly describes 'submit my search query'.

This is a CORS issue for the cloudfront service.

**Comment by nigelbabu** [comment]
Okay, so this was a CORS issue. We need to forward the Origin header on cloudfront to get it working. Considering it works on staging, I'm happy to mark as closed. I've updated production cloudfront distribution and requested a cache invalidation of those two files. It should be fixed in a bit.

**Comment by nigelbabu** [comment]
Fixed!

**Comment by macoo222** [comment]
Ok
