### ISSUE TITLE
Links on /about/team

### ISSUE THREAD

**Issue by adamamyl** [okfn/foundation#241]
It would be super-useful if I could link to:

 - [x] an individual on a page (e.g., https://okfn.org/about/team#rufuspollock)
 - [ ] a team on the page (e.g., https://okfn.org/about/team#commercial)

can haz?

**Comment by Deiz** [comment]
Adding IDs to the team headings seems easy enough, but how would the teams be linked to?

Perhaps it could be done similarly to what Sphinx does, where a clickable symbol appears when hovering over section headings (e.g. http://ops.okfn.org/).

**Comment by morchickit** [comment]
WONTIX - team has changed.
