### ISSUE TITLE
No logos or media available on the new site

### ISSUE THREAD

**Issue by amercader** [okfn/foundation#250]
The only thing available is a link to the [old media page](http://webarchive.okfn.org/okfn.org/201404/media/) on the press section, with old logos.

**Comment by morchickit** [comment]
@smth and @ljoelle - can we update this to the new logos and branding? under the resource heading?

**Comment by ljoelle** [comment]
I believe @smth and @pwalsh are working on this sometime this week

**Comment by morchickit** [comment]
@smth - close this issue after we are sorting the branding repository for this site. thanks!

**Comment by smth** [comment]
We now have logos at least https://okfn.org/press/resources/
