### ISSUE TITLE
The green is inconsistant with our logo (and quite garish)

### ISSUE THREAD

**Issue by smth** [okfn/foundation#259]
I propose (again) that we change our primary web colour. My suggestion is `#69b93b`.

Current colour:
![old-green](https://cloud.githubusercontent.com/assets/1375708/15174405/7bb4a32e-1759-11e6-93fd-7c625bed55f2.jpg)

Proposed colour:
![green](https://cloud.githubusercontent.com/assets/1375708/15174362/34df02c8-1759-11e6-940e-8ff1dbb013df.jpg)

(Relates to https://github.com/okfn/app-theme/issues/9)

**Comment by morchickit** [comment]
Agreed. Go for it!

**Comment by pwalsh** [comment]
👍

**Comment by morchickit** [comment]
@smth - can we close this?

**Comment by smth** [comment]
Sure
